### ISSUE TITLE
Idea: Support children after attributes using __getitem__

### ISSUE THREAD

**Issue by bessey** [paveldedik/ludic#19] opened 2024-03-30 22:24 UTC
This idea is inspired by [htpy](https://github.com/pelme/htpy) which I learned of in the same HN thread I learned of ludic 😄 

`htpy` solves the "cant have attributes before variables number of child arguments" problem by some _creative_ use of `__getitem__` and `return self`.

Toying around it seems like it would be quite simple to introduce this same pattern to Ludic, if there was any appetite:
https://github.com/bessey/ludic/pull/1/files

Personally I think its worth introducing this entirely optional API, unusual as it is, as it brings the syntax closer to raw HTML where attributes always come first. What are your thoughts?

**Comment by paveldedik** [comment] 2024-04-02 09:30
Hi, thank you for the issue, first I have to say I really like this idea. For some reason, I completely missed `htpy` until now. It has a very similar approach. 

In fact, at first, I had a very similar idea to `htpy`. I implemented Ludic in a way that you would create elements like this:

- `Link(to="https://example.com)("Click here")`

I did that by overriding `__call__`. I like the usage of `div[div(id="test")[...]]` even more. However, I learned this has a few flaws:

1. I cannot properly type-check this since I want to be able to define what kind of children an element can have - the problem is that `TChildren` TypeVar must be covariant. This is the biggest issue, mypy complains about "TypeVar is covariant but used as a parameter" in the `__call__` method, the same happens for `__getitem__`.
2. It makes the way of working with elements as Python objects a bit less intuitive. In case I override `__getitem__`, I now cannot do `page[0]` to get the first child or `page["id"]` to get the ID of the element. This behavior is currently not implemented in Ludic but I was thinking about that a lot and I think I'll implement it like that.

I think the biggest issue is the first one. If I was able to solve that somehow, I would consider implementing it like in `htpy`. I am also afraid that in the future, this magic way of overriding the standard behavior of the `__getitem__` method could lead to more problems with type-checkers.

Thank you very much for the showcase, I was testing it again with your solution to make sure there isn't a solution for the problems I described above. Unfortunately, I couldn't make it work.

If you have more suggestions or anything, I'll gladly hear them :)

**Comment by bessey** [comment] 2024-04-04 17:16
I think `htpy` came out literally last week so not too surprising.

Both flaws make sense to me but I am not Python typings are not my strong suit, so I don't think I'll be much help suggestions wise 😅. I'm just a Ruby-ist considering a tech stack change and learning the SOTA elsewhere.

I guess I'll CC @pelme in case there's an interest in collaboration.

**Comment by pelme** [comment] 2024-04-04 19:53
1. I have not tried to solve type checking attributes or children and cannot really help with that. We are doing both a bunch of custom elements/web components, Alpine.js and htmx so we are (ab)using custom attributes/elements pretty much everywhere. We get a lot of value from using typed Python with our components by creating typed component wrappers(functions) that accept more narrow types. And then having mypy check all of our internal objects used to construct htpy objects is very useful.
2. I did not have use case for accessing the children or attributes of an element yet. Attributes and children are "private" in htpy right now but that could be changed, so maybe using `element.attrs["x"]` or `element.children[0]` would be a nice way to get them. They can be found like this now:
```py
>>> e = div('#hi')[("a", "b")]
>>> e._attrs["id"]
'hi'
>>> e._children[0]
'a'
>>> e._children[1]
'b'
```

(The idea for using `__getitem__`/`[]` for HTML elements has been around some 20 years since at least `nevow.stan`. Looked for existing libraries but mostly found a unmaintained projects. Created htpy to explore these ideas in our company. htpy has been around for ~6 months but probably only used internally in our company. :) Published the docs the last couple of weeks to make it usable for others too. Was really happy when I read about Ludic on HN that uses the same ideas for creating HTML without templates. Will be happy to explore ideas related to this more!)

**Comment by paveldedik** [comment] 2024-04-08 07:54
Thank you @pelme for the answer. Yeah I noticed that the first point is probably not relevant for htpy. About the second point, there is also the need to optionally specify types of `Table` children, e.g.:

```python
Table[PersonHead, PersonRow](
  PersonHead("Id", "Name"),
  PersonRow("1", "Joe"),
  PersonRow("2", "Jane"),
)
```

But I'm not sure whether this would be possible in `htpy` while overriding the `__getattr__` method. htpy doesn't seem to care about types of children of elements/components that much while in ludic, I want to explore this possibility a bit more - but I'm still not sure it will be that useful.

BTW I think I've been thinking about similar library for quite some time, maybe I'm a bit surprised there was never really a popular library that does this. Perhaps together with HTMX.org, combined with Python's richer type system, writing HTML in pure Python offers a viable alternative for generating HTML within Python code. But who knows if it can ever at least partially rival Jinja2's established position.

**Comment by paveldedik** [comment] 2024-04-19 17:08
I'll close this issue for now, if there are plans to change the behavior in future, I'll open a new one.

Thank you for the discussion and feel free to open new issues or share other ideas :)

**Closed by paveldedik** 2024-04-19 17:08 UTC
